### ISSUE TITLE
if the reports are html scrape them

### ISSUE THREAD

**Issue by fgregg** [labordata/lm20#7]

**Comment by ethangalebach** [comment]
Hi Forest,

I noticed your parse_html branch seems to have done this. Is there anything left to be done on that branch before it is merged?

p.s. I love all the repos in this project. If you are ever looking for contributions on any easy and well-defined issues anywhere in the project, I'd love to give it a go!

**Comment by fgregg** [comment]
yes, we need to adjust get the output from those forms into tables in the database. if you'd like to help with that, that would be great!

**Comment by fgregg** [comment]
this is blocked until https://github.com/jsnell/json-to-multicsv/issues/3 is addressed, or we route around that bug
